import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/prism-themes@1.9.0/themes/prism-vsc-dark-plus.min.css"
        />
      </head>
      <body className="dark bg-background text-foreground font-sans leading-relaxed">
        {/* …header / footer … */}
        {children}
      </body>
    </html>
  );
}
